import img1 from '../../assets/carousell/image1.jpg';
import img2 from '../../assets/carousell/image2.jpg';
import img3 from '../../assets/carousell/image3.jpg';

export const hotelData = [
    {
        _id: 11,
        slogan: 'Only 1 room left at this price on our site',
        title: 'Jumeirah Mina A Salam',
        location: 'Madinat Jumeirah, Al Sufouh Rd, Dubai',
        facility1: 'Pool',
        facility2: 'Hot Tub',
        facility3: 'King Bed',
        feature1: 'Fully Refundable',
        feature2: 'Reserve now, pay later',
        price: '$400',
        star: '5',
        point: '9.4',
        review: '983',
        include: 'taxes & fees',
        img1: img1,
        img2: img2,
        img3: img3,
    },
    {
        _id: 12,
        slogan: 'Only 1 room left at this price on our site',
        title: 'Jumeirah Mina A Salam',
        location: 'Madinat Jumeirah, Al Sufouh Rd, Dubai',
        facility1: 'Pool',
        facility2: 'Hot Tub',
        facility3: 'King Bed',
        feature1: 'Fully Refundable',
        feature2: 'Reserve now, pay later',
        price: '$400',
        star: '5',
        point: '9.4',
        review: '983',
        include: 'taxes & fees',
        img1: img1,
        img2: img2,
        img3: img3,
    },
    {
        _id: 13,
        slogan: 'Only 1 room left at this price on our site',
        title: 'Jumeirah Mina A Salam',
        location: 'Madinat Jumeirah, Al Sufouh Rd, Dubai',
        facility1: 'Pool',
        facility2: 'Hot Tub',
        facility3: 'King Bed',
        feature1: 'Fully Refundable',
        feature2: 'Reserve now, pay later',
        price: '$400',
        star: '5',
        point: '9.4',
        review: '983',
        include: 'taxes & fees',
        img1: img1,
        img2: img2,
        img3: img3,
    },
    {
        _id: 14,
        slogan: 'Only 1 room left at this price on our site',
        title: 'Jumeirah Mina A Salam',
        location: 'Madinat Jumeirah, Al Sufouh Rd, Dubai',
        facility1: 'Pool',
        facility2: 'Hot Tub',
        facility3: 'King Bed',
        feature1: 'Fully Refundable',
        feature2: 'Reserve now, pay later',
        price: '$400',
        star: '5',
        point: '9.4',
        review: '983',
        include: 'taxes & fees',
        img1: img1,
        img2: img2,
        img3: img3,
    },
    {
        _id: 15,
        slogan: 'Only 1 room left at this price on our site',
        title: 'Jumeirah Mina A Salam',
        location: 'Madinat Jumeirah, Al Sufouh Rd, Dubai',
        facility1: 'Pool',
        facility2: 'Hot Tub',
        facility3: 'King Bed',
        feature1: 'Fully Refundable',
        feature2: 'Reserve now, pay later',
        price: '$400',
        star: '5',
        point: '9.4',
        review: '983',
        include: 'taxes & fees',
        img1: img1,
        img2: img2,
        img3: img3,
    },
    {
        _id: 16,
        slogan: 'Only 1 room left at this price on our site',
        title: 'Jumeirah Mina A Salam',
        location: 'Madinat Jumeirah, Al Sufouh Rd, Dubai',
        facility1: 'Pool',
        facility2: 'Hot Tub',
        facility3: 'King Bed',
        feature1: 'Fully Refundable',
        feature2: 'Reserve now, pay later',
        price: '$400',
        star: '5',
        point: '9.4',
        review: '983',
        include: 'taxes & fees',
        img1: img1,
        img2: img2,
        img3: img3,
    },
    {
        _id: 17,
        slogan: 'Only 1 room left at this price on our site',
        title: 'Jumeirah Mina A Salam',
        location: 'Madinat Jumeirah, Al Sufouh Rd, Dubai',
        facility1: 'Pool',
        facility2: 'Hot Tub',
        facility3: 'King Bed',
        feature1: 'Fully Refundable',
        feature2: 'Reserve now, pay later',
        price: '$400',
        star: '5',
        point: '9.4',
        review: '983',
        include: 'taxes & fees',
        img1: img1,
        img2: img2,
        img3: img3,
    },
    {
        _id: 18,
        slogan: 'Only 1 room left at this price on our site',
        title: 'Jumeirah Mina A Salam',
        location: 'Madinat Jumeirah, Al Sufouh Rd, Dubai',
        facility1: 'Pool',
        facility2: 'Hot Tub',
        facility3: 'King Bed',
        feature1: 'Fully Refundable',
        feature2: 'Reserve now, pay later',
        price: '$400',
        star: '5',
        point: '9.4',
        review: '983',
        include: 'taxes & fees',
        img1: img1,
        img2: img2,
        img3: img3,
    },
   
]